name: Publish to (Test)PyPI

on:
  push:
    branches: ["**"]         # corre en cada commit a cualquier rama
    tags:
      - 'test-*'             # ej: test-0.1.0 -> TestPyPI
      - 'v*'                 # ej: v0.1.0     -> PyPI
  pull_request:              # opcional: corre en PRs también
  workflow_dispatch:         # opcional: permitir ejecutar manualmente

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Upload dist as artifact (always)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

      # Publica a TestPyPI solo si el push fue un tag que empieza con test-
      - name: Publish to TestPyPI (tags test-*)
        if: github.event_name == 'push' && startsWith(github.ref_name, 'test-')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

      # Publica a PyPI solo si el push fue un tag que empieza con v
      - name: Publish to PyPI (tags v*)
        if: github.event_name == 'push' && startsWith(github.ref_name, 'v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
